yatube/about/urls.py
from django.urls import path
from . import views # импорты не по pep8


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
# импорты не по pep8
from django.urls import path
from . import views

app_name = 'posts'


# удали учебные комментарии
urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Страница с постами выбраной группы
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
# импорты не по pep8
from django.contrib.auth.views import LoginView, LogoutView

from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout',
    ),
    path(
        'signup/', views.SignUp.as_view(), name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
# импорты не по pep8
from django.db import models

from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        help_text="Заполнение данного поля является обязательным",
        verbose_name="Текст поста",
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        help_text="Выбрать группу (не обязательно)",
        verbose_name="Группа"
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date'] # Для неизменяемых последовательностей лучше использовать `tuple` https://www.programiz.com/python-programming/list-vs-tuples
        default_related_name = 'posts'


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=50, null=False, unique=True) # не нужно указывать max_length для SlugField, по умолчанию он уже 50 символов. Указываем, только если нужно имзенить. `null=False,` уже идет по умолчанию. Лишний флаг
    description = models.TextField()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    text = models.TextField(
        help_text="Напишите комментарий",
        verbose_name="Комментарий",
    )
    created = models.DateTimeField(
        "Время добавления комментария",
        auto_now_add=True,
    )

    class Meta:
        default_related_name = 'comments'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_author_user_following'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')
        labels = {
            'text': 'Текст поста',
            'group': 'Группа',
            'image': 'Картинка'
        }
        help_texts = {
            'text': 'Напишите текст (обязательно)',
            'group': 'Укажите группу (не обязательно)',
            'image': 'Загрузить изображение',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': 'Комментарий'}
        help_texts = {'text': 'Напишите комментарий'}

yatube/posts/views.py
# импорты не по зуз8
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from django.shortcuts import render, get_object_or_404, redirect

from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm


def index(request):
    post_list = Post.objects.all().select_related('author') # стоит также сделать связь с `group`, чтобы избежать лишних хинтов в БД
    page_obj = paginator(request, post_list)
    title = 'Главная страница сайта Yatube' # Не стоит превращать view в передачу статичных аргументов в шаблон. Используй `block title` для переопределения нужного блока. https://docs.djangoproject.com/en/4.0/ref/templates/language/#templates
    context = {
        'page_obj': page_obj,
        'title': title
    }
    template = 'posts/index.html' # Нет необходимости выносить в отдельную переменную template, можно сразу прокинуть шаблон в render() вторым аргументом- читабельность не потеряется.
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:10] # обрезка постов должна быть в отпагинированном объекте `page_obj`. Сейчас же в пагинацию не попадет никогда больше 10 постов группы
    page_obj = paginator(request, posts)
    context = {
        'group': group,
        'posts': posts, # вот это лишнее. Все объекты передаем в `page_obj`, отпагинированными.
        'page_obj': page_obj
    }
    template = 'posts/group_list.html'
    return render(request, template, context)


def profile(request, username):
    author = User.objects.get(username=username) # Используй `get_object_or_404(...)`, чтобы в случае отсутствия модели была 404 страничка. https://docs.djangoproject.com/en/4.0/topics/http/shortcuts/#get-object-or-404
    post_list = author.posts.all() # выборку принято называть с префиксом `queryset` `posts_queryset`, например. Тут же не список постов. Было бы здорово использовать `select_related`
    page_obj = paginator(request, post_list)
    title = f'Профайл пользователя {username}' # убрать в block tittle
    all_posts = post_list.count() # дай подходящий нейминг. тут хранится `количество` постов

    following = (
        request.user.is_authenticated
        and Follow.objects.filter( # выборка `Follow` должна проверять: подписан ли `текущий пользователь` на `автора`. Должно быть комплексное условие по двум полям
            author__following__user=request.user
        ).exists()
    )
    context = {
        'page_obj': page_obj,
        'title': title,
        'all_posts': all_posts,
        'author': author,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    posts_count = post.author.posts.count()
    context = {
        'title': post.text, # пост уже передается, не нужно отдельно вытягивать его атрибуты во вьюхе. Это можно сделать прямо в б=шаблоне
        'post_count': posts_count,
        'post': post,
        'comments': post.comments.all(),
        'form': CommentForm(),
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None,
                    files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author)
    context = {
        'form': form,
        'is_edit': False # не обязательно передавать. Ошибки в шаблоне не будет, если переменной нет.
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    # Тут происходит лишний хинт в БД. Есть несколько вариантов избежать этого:
    #
    #  - Использовать `select_related`, подгружая нужные поля заранее;
    #  - Сравнивать не модели, а их `id` `request.user !=edit_post.author_id`
    #
    # https://docs.djangoproject.com/en/4.1/ref/models/querysets/#select-related
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
        'is_edit': True,
        'post': post
    }
    return render(request, 'posts/create_post.html', context)

# утилитам самое место в отдельном файле, например, `utils.py`. Во `views.py` только вьюхи
def paginator(request, posts):
    paginator = Paginator(posts, 10) # 10 вынеси в константу в settings.py, например
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, pk=post_id)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(
        author__following__user=request.user or None # or None в выборке никак не поможет. Тут формируется queryset, а не форма
    ).all()
    page_obj = paginator(request, post_list)
    return render(
        request,
        'posts/follow.html',
        context={'page_obj': page_obj,
                 }
    )


@login_required
def profile_follow(request, username):
    author = User.objects.get(username=username) # get_object_or_404
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=author.username)


@login_required
def profile_unfollow(request, username):
    author = User.objects.get(username=username) # get_object_or_404
    following = Follow.objects.filter(user=request.user, author=author)
    if following: # exists(), чтобы просто проверить существование объектов, а не тянуть их из БД
        following.delete()
    return redirect('posts:profile', username=author.username)

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p> {#Забыла закрывающий тег для footer#}

yatube/templates/includes/header.html
{% load static %}
<header>
    <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
    <!-- В дальнейшем тут будет создано полноценное меню -->
    <nav class="navbar navbar-light" style="background-color: hsl(22, 100%, 95%)">
      <div class="container">
        <a class="navbar-brand" href="index.html">
          <img src="{% static 'img/logo.png' %}" width="250" height="100" class="d-inline-block align-top" alt="">
        </a>
        {% comment %}
      Меню - список пунктов со стандартными классами Bootsrap.
      Класс nav-pills нужен для выделения активных пунктов 
      {% endcomment %}
      {% with request.resolver_match.view_name as view_name %} 
      <ul class="nav nav-pills">
        <li class="nav-item">              
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
             href="{% url 'about:author' %}"
          >
            Об авторе
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
          href="{% url 'about:tech' %}"
          >
          Технологии
        </a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
          href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'password_change' %}active{% endif %}" 
          href="{% url 'password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'users:logged_out' %}active{% endif %}" 
          href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li class="nav-item">
          Пользователь:<br> {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}" 
          href="{% url 'users:login' %}"
          >Войти</a>
        </li>
        <li class=""> 
          <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}" 
          href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
        {% endwith %} 
      </ul>
      </div>
    </nav>
</header>
  

yatube/templates/includes/post.html
{% load thumbnail %}
          <article> 
            <ul> 
              <li> Автор: 
                <a href="{% url 'posts:profile' post.author.username %}">
                {{ post.author.get_full_name }}
                </a> 
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
           <p>{{ post.text }}</p> {# Вероятно тут должна быть обрезка текста, если далее идет детализация? #}
            <a href="{% url 'posts:post_detail' post.id %}"> Полный текст.
            </a>
            <br>
            <p>
            {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}"> Все записи группы {{post.group.title}}
            </a>
            <br>
            {% endif %}
          </p>
          </article>
          {% if not forloop.last %}<hr>{% endif %}